---
id: com.steadybit.extension_prometheus.instance
label:
  one: Prometheus instance
  other: Prometheus instances
icon: |
  <svg
    viewBox="0 0 24 25"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M12 2.5c-5.522 0-10 4.477-10 10s4.478 10 10 10c5.523 0 10-4.477 10-10s-4.477-10-10-10zm0 18.716c-1.571 0-2.845-1.05-2.845-2.344h5.69c0 1.294-1.273 2.344-2.845 2.344zm4.7-3.12H7.3V16.39h9.4v1.705zm-.034-2.582H7.327c-.031-.036-.063-.071-.093-.108-.962-1.168-1.189-1.778-1.409-2.4-.003-.02 1.167.24 1.997.427 0 0 .427.098 1.051.212-.599-.702-.955-1.596-.955-2.509 0-2.004 1.538-3.756.983-5.172.54.044 1.117 1.14 1.156 2.852.574-.793.814-2.241.814-3.13 0-.919.606-1.987 1.212-2.023-.54.89.14 1.653.745 3.547.226.71.197 1.908.373 2.667C13.258 8.3 13.53 6 14.53 5.206c-.441 1 .065 2.251.411 2.853.56.97.898 1.706.898 3.097 0 .932-.344 1.81-.925 2.496.66-.123 1.116-.235 1.116-.235l2.145-.418s-.312 1.28-1.509 2.515z"
      fill="currentColor"
    />
  </svg>
category: monitoring
extension: com.steadybit.extension_prometheus
